# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up virtual X11
      run: sudo apt-get install xvfb
    - name: Start virtual frame buffer
      run: Xvfb :19 -screen 0 1024x768x16 &
    - name: set display
      run: export DISPLAY=:19
    - name: Build with Maven
      #run: mvn --file pom.xml -Pcodecoverage -B package "-Djava.awt.headless=true"  
      run: mvn --file pom.xml -Pcodecoverage -B package 
      env:  
        CUCUMBER_PUBLISH_TOKEN: c31ffecc-9b74-4445-9817-60ec7f923927
